version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "7777:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=csyl1234
      - MYSQL_DATABASE=gogs
      - MYSQL_USER=gogs
      - MYSQL_PASSWORD=csyl1234
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/config.cnf:/etc/mysql/conf.d/mysql.cnf
  gogs:
    image: gogs/gogs
    # image: gogs/gogs:0.11.66
    restart: always
    ports:
      - "80:3000"
      - "10022:22"
    volumes:
      - ./data:/data
      - ./public:/app/gogs/public
      - ./templates:/app/gogs/templates
    links:
      - mysql
    depends_on:
      - mysql
